Ferramenta_Scrumt/Controllers/EquipeController.cs
using Ferramenta_Scrumt.FILTERS;
using Ferramenta_Scrumt.MODEL;
using Ferramenta_Scrumt.REPOSITORIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ferramenta_Scrumt.Controllers
{
    [Authorize]
    [Filterlisttest]
    public class EquipeController : Controller
    {
        
        List<Users> UsersList;
        List<Equipe> EquiList;
        EquipeRepositorio _EquiRep = new EquipeRepositorio();
        UsersRepositorio _UsersRep = new UsersRepositorio();
        List<Projeto> ProjList;
        ProjetoRepositorio _ProjRep = new ProjetoRepositorio();


        private void CarregaLista()
        {
            EquiList = _EquiRep.Lista(new EquipeMapper());
            Session["Lista"] = EquiList;
        }
        public ActionResult Index()
        {
            CarregaLista();

            return View(EquiList);
        }
        [HttpPost]
        public ActionResult Create(Equipe E)
        {
            _EquiRep.ADD(E);
            Session["Lista"] = EquiList;
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {
            CarregaLista();
            ProjList = _ProjRep.ListaProj(new ProjetoMapper(), "Select top 1 ID_Projeto,Descricao, Data_Inicio, Data_Fim from Projeto order by ID_Projeto desc");
            ViewBag.Projeto = new SelectList(ProjList, "ID", "Descricao");

            UsersList = _UsersRep.Lista(new UsersMapper());
            ViewBag.Nome_Membro = new SelectList(UsersList, "ID", "Nome");
            return View();
        }

    }
}

Ferramenta_Scrumt/Controllers/ProjetoController.cs
using Ferramenta_Scrumt.FILTERS;
using Ferramenta_Scrumt.MODEL;
using Ferramenta_Scrumt.REPOSITORIO;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Ferramenta_Scrumt.Controllers
{
    [Filterlisttest]
    [Authorize]
    public class ProjetoController : Controller
    {
        // GET: Projeto
        List<Projeto> ProjetoList;
        ProjetoRepositorio _ProjetoRep = new ProjetoRepositorio();
        List<Users> UsersList;
        UsersRepositorio _UsersRep = new UsersRepositorio();

        private void CarregaLista()
        {
            List<Equipe> Equipes = (List<Equipe>)Session["Equipes"];

            ProjetoList = _ProjetoRep.Lista(new ProjetoMapper(),Equipes);
            Session["Lista"] = ProjetoList;
        }
        public ActionResult Index()
        {
            CarregaLista();
            return View(ProjetoList);
        }
        public ActionResult Create()
        {
            CarregaLista();
            UsersList = _UsersRep.Lista(new UsersMapper());
            ViewBag.Nome_Membro = new SelectList(UsersList, "ID", "Nome");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Projeto P)
        {
            CarregaLista();
            _ProjetoRep.ADD(P);
            Session["Lista"] = ProjetoList;
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            CarregaLista();
            return View(ProjetoList.Where(X => X.ID == id).First());
        }
        [HttpPost]
        public ActionResult Delete(Projeto P)
        {
            CarregaLista();
            _ProjetoRep.Delete(ProjetoList.Where(X => X.ID == P.ID).First());
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            CarregaLista();
            //passando uma model P
            Projeto P = ProjetoList.Where(X => X.ID == id).First();
            CarregaLista();
            return View(P);
        }
        [HttpPost]
        public ActionResult Edit(Projeto P)
        {
            //carrega lista e traz um objeto da lista para ser editado

            _ProjetoRep.Update(P);
            CarregaLista();
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            CarregaLista();
            return View(ProjetoList.Where(X => X.ID == id).First());
        }
    }
}

Ferramenta_Scrumt/Views/Projeto/Create.cshtml
@model Ferramenta_Scrumt.MODEL.Projeto


@{
    ViewBag.Title = "Adicionar Projeto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-heading">
    <h3>
        Projeto
    </h3>
    <ul class="breadcrumb">
        <li>
            <a href="/Home/Index">Home</a>
        </li>
        <li>
            <a href="/Projeto/Index">Projetos</a>
        </li>
        <li class="active">Adicionar Projeto</li>
    </ul>
</div>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        
                        <section class="panel">
                            <header class="panel-heading custom-tab">
                                <ul class="nav nav-tabs">
                                    <li class="active">
                                        <a href="#home2" data-toggle="tab">Projeto</a>
                                    </li>
                                    <li class="">
                                        <a style="cursor:pointer" onclick="location.href='@Url.Action("Create", "Equipe")'" data-toggle="tab">Membros</a>
                                </ul>
                            </header>
                            <div class="panel-body">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="home2">
                                        <div class="panel-body">
                                            <form role="form">
                                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                <div class="form-group col-md-12">
                                                    @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                                                </div>
                                                <div class="form-group col-md-6">
                                                    @Html.LabelFor(model => model.Data_Inicio, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    @Html.EditorFor(model => model.Data_Inicio, new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Data_Inicio, "", new { @class = "text-danger" })
                                                </div>
                                                <div class="form-group col-md-6">
                                                    @Html.LabelFor(model => model.Data_Fim, htmlAttributes: new { @class = "control-label col-md-2" })
                                                    @Html.EditorFor(model => model.Data_Fim, "datefim", new { htmlAttributes = new { @class = "form-control" } })
                                                    @Html.ValidationMessageFor(model => model.Data_Fim, "", new { @class = "text-danger" })
                                                </div>

                                            </form>
                                           
                                        </div>
                                    </div>
                                    <div class="tab-pane" id="about2">
                                        <div class="container">
                                            <br>
                                            <h4>
                                                Equipe
                                            </h4>
                                            @Html.DropDownList("Nome_Membro", new SelectList(ViewBag.Nome_Membro, "Value", "Text"), htmlAttributes: new { @id = "pre-selected-options", multiple = "multiple" })
                                            <br>
                                        </div>
                                        <hr>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Adicionar" class="btn btn-primary" />
                                    @Html.ActionLink("Voltar", "Index", 0, new { @class = "btn btn-danger" })
                                </div>
                            </div>
                            
                        </section>
                         
                    </section>
                </div>
            </div>
        </section>
    }

</body>

Ferramenta_Scrumt/Views/Projeto/Delete.cshtml
@model Ferramenta_Scrumt.MODEL.Projeto

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-heading">
    <h3>
        Projeto
    </h3>
    <ul class="breadcrumb">
        <li>
            <a href="/Home/Index">Home</a>
        </li>
        <li>
            <a href="/Users/Index">Projeto</a>
        </li>
        <li class="active">Deletar Projeto</li>
    </ul>

</div>

<body>
    <div class="wrapper">
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        <h3>Deseja Realmente Excluir este Registro?</h3>
                        <div>
                            <hr />
                            <dl class="dl-horizontal">
                                <dt>
                                    @Html.DisplayNameFor(model => model.Descricao)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Descricao)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Data_Inicio)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Data_Inicio)
                                </dd>
                                <dt>
                                    @Html.DisplayNameFor(model => model.Data_Fim)
                                </dt>

                                <dd>
                                    @Html.DisplayFor(model => model.Data_Fim)
                                </dd>
                            </dl>

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-actions no-color">
                                    <input type="submit" value="Deletar" class="btn btn-danger" />
                                    @Html.ActionLink("Voltar", "Index", 0, new { @class = "btn btn-success" })
                                </div>
                            }
                        </div>
                    </header>
                </section>
            </div>
        </div>
    </div>
</body>

Ferramenta_Scrumt/Views/Projeto/Details.cshtml
@model Ferramenta_Scrumt.MODEL.Projeto

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-heading">
    <h3>
        Projeto
    </h3>
    <div class="col-md-10 col-xs-8">
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Cadastros</a>
            </li>
            <li class="#">Projeto</li>
            <li class="active">Detalhes</li>
        </ul>
    </div>

</div>
<div class="wrapper">
    <div class="row">
        <div class="col-sm-12">
            <section class="panel">
                <header class="panel-heading">
                    <h4>Detalhes do Projeto @Html.DisplayFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })</h4>
                    <hr />
                    <div class="panel-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.DisplayFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descricao, "Projeto: ", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.DisplayFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Data_Inicio, "Data Ínicio: ", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.DisplayFor(model => model.Data_Inicio, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Data_Fim, "Data Fim: ", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.DisplayFor(model => model.Data_Fim, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </header>
            </section>
            @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "btn btn-info" }) |
            @Html.ActionLink("Voltar", "Index", 0, new { @class = "btn btn-danger" })
        </div>

    </div>
</div>

Ferramenta_Scrumt/Views/Projeto/Edit.cshtml
@model Ferramenta_Scrumt.MODEL.Projeto

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-heading">
    <h3>
        Equipe
    </h3>
    <ul class="breadcrumb">
        <li>
            <a href="/Home/Index">Home</a>
        </li>
        <li>
            <a href="/Users/Index">Projeto</a>
        </li>
        <li class="active">Editar Projeto</li>
    </ul>

</div>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <section class="wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Editar Membro
                        </header>
                        <div class="panel-body">
                            <form role="form">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.ID, htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.DisplayFor(model => model.ID, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ID, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Descricao, "Descrição do Projeto", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Data_Inicio, "Data Início", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.EditorFor(model => model.Data_Inicio, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Data_Inicio, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Data_Fim,"Data Fim", htmlAttributes: new { @class = "control-label col-md-2" })
                                    @Html.EditorFor(model => model.Data_Fim, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Data_Fim, "", new { @class = "text-danger" })
                                </div>
                            </form>
                            <div class="form-group">
                                <input type="submit" value="Salvar" class="btn btn-success" />
                                @Html.ActionLink("Voltar", "Index", 0, new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
    }

</body>

Ferramenta_Scrumt/Views/Projeto/Index.cshtml
@model IEnumerable<Ferramenta_Scrumt.MODEL.Projeto>

@{
    ViewBag.Title = "Projetos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="page-heading">
    <h3>
        Projetos
    </h3>
    <div class="col-md-10 col-xs-6">
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Cadastros</a>
            </li>
            <li class="active">Projeto</li>
        </ul>
    </div>
    <div class="col-md-2 col-xs-4">
        <p>
            @Html.ActionLink("Adicionar Projeto", "Create", 0, new { @class = "btn btn-primary" })
        </p>
    </div>
</div>
<div class="wrapper">
    <div class="row">
        <div class="col-xs-12">
            <section class="panel">
                <header class="panel-heading">
                    Projetos Cadastrados
                    <span class="tools pull-right">
                        <a href="javascript:;" class="fa fa-chevron-down"></a>
                    </span>
                </header>
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    <div class="col-md-3 col-xs-3">
                                        @Html.DisplayNameFor(model => model.Descricao)
                                    </div>
                                    <div class="col-md-3 col-xs-4">
                                        @Html.DisplayNameFor(model => model.Data_Inicio)
                                    </div>
                                    <div class="col-md-3 col-xs-3">
                                        @Html.DisplayNameFor(model => model.Data_Fim)
                                    </div>
                                </th>
                            </tr>
                        </thead>
                        @foreach (var item in Model)
                        {
                            <tbody>
                                <tr>
                                    <td>
                                        <div class="col-md-3 col-xs-3">
                                            <b class="hidden-md hidden-lg">
                                            </b>@Html.DisplayFor(modelItem => item.Descricao)
                                        </div>
                                        <div class="col-md-3 col-xs-4">
                                            <b class="hidden-md hidden-lg">
                                            </b>@Html.DisplayFor(modelItem => item.Data_Inicio)
                                        </div>
                                        <div class="col-md-3 col-xs-3">
                                            <b class="hidden-md hidden-lg">
                                            </b>@Html.DisplayFor(modelItem => item.Data_Fim)
                                        </div>
                                        <div class="col-md-3 col-xs-12">

                                            @Html.ActionLink("Editar", "Edit", new { id = item.ID }, new { @class = "btn btn-success" })
                                            @Html.ActionLink("Detalhes", "Details", new { id = item.ID }, new { @class = "btn btn-info" })
                                            @Html.ActionLink("Deletar", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })

                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        }
                    </table>
                </div>
            </section>
        </div>
    </div>
</div>

