Ferramenta_Scrumt/Controllers/QuadrotarefasController.cs
using Ferramenta_Scrumt.FILTERS;
using Ferramenta_Scrumt.MODEL;
using Ferramenta_Scrumt.REPOSITORIO;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Ferramenta_Scrumt.Controllers
{
    [Authorize]
    [Filterlisttest]
    public class QuadrotarefasController : Controller
    {
        // GET: Quadrotarefas
        List<Quadro_tarefas> QtarefasList;
        QuadrotarefasRepositorio _QtarefasRep = new QuadrotarefasRepositorio();
        List<Projeto> ProjetoList;
        ProjetoRepositorio _ProjetoRep = new ProjetoRepositorio();

        private void CarregaLista()
        {
            List<Equipe> Equipes = (List<Equipe>)Session["Equipes"];
            QtarefasList = _QtarefasRep.Listaquadro(new QuadrotarefasMapper(), "Select [Product_Backlog].[Historia],[Projeto].ID_Projeto,[Projeto].[Descricao],[Product_Release].[ID_PBacklog],[Situacao_Quadrotarefas], [Product_Backlog].[Importancia] from Product_Release Inner Join Product_Backlog on Product_Release.ID_PBacklog = Product_Backlog.ID_PBacklog Inner Join Projeto on Product_Backlog.ID_Projeto = Projeto.ID_Projeto group by Historia,Descricao,Projeto.ID_Projeto, Product_Backlog.ID_PBacklog, Product_Release.ID_PBacklog, Situacao_QuadroTarefas, Importancia", Equipes);
            Session["Lista"] = QtarefasList;
        }
        public ActionResult Index()
        {
            CarregaLista();
            List<Equipe> Equipes = (List<Equipe>)Session["Equipes"];
            ProjetoList = _ProjetoRep.Lista(new ProjetoMapper(),Equipes);
            ViewBag.Projeto = new SelectList(ProjetoList, "ID", "Descricao");
            return View(QtarefasList);
        }
        public ActionResult Details(int id)
        {
            CarregaLista();
            return View(QtarefasList.Where(X => X.id_Pbacklog == id).First());
        }
    }
}

Ferramenta_Scrumt/Controllers/ReleaseBacklogController.cs
using Ferramenta_Scrumt.FILTERS;
using Ferramenta_Scrumt.MODEL;
using Ferramenta_Scrumt.REPOSITORIO;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Ferramenta_Scrumt.Controllers
{
    [Authorize]
    [Filterlisttest]
    public class ReleaseBacklogController : Controller
    {
        // GET: ReleaseBacklog
        List<ReleaseBacklog> RBacklogList;
        ReleaseBacklogRepositorio _RBacklogRep = new ReleaseBacklogRepositorio();
        List<ProductBacklog> ProductList;
        ProductBacklogRepositorio _ProductRep = new ProductBacklogRepositorio();
        List<Users> UserList;
        UsersRepositorio _UserRep = new UsersRepositorio();

        private void CarregaLista()
        {
            RBacklogList = _RBacklogRep.Lista(new ReleaseBacklogMapper());
            Session["Lista"] = RBacklogList;
        }
        public ActionResult Index()
        {
            CarregaLista();
            return View(RBacklogList);
        }
        [HttpGet]
        public ActionResult Create()
        {
            CarregaLista();
            List<Equipe> Equipes = (List<Equipe>)Session["Equipes"];
            UserList = _UserRep.Lista(new UsersMapper());
            ViewBag.Nome = new SelectList(UserList, "ID", "Nome");
            ProductList = _ProductRep.Lista(new ProductBacklogMapper(), Equipes);
            ViewBag.Historia = new SelectList(ProductList, "ID", "Historia");

            ViewBag.Situacao = new List<SelectListItem>
            {
                new SelectListItem{Text = "A Fazer", Value = "A Fazer"},
                new SelectListItem{Text = "Em Execução", Value = "Em Execução"},
                new SelectListItem{Text = "Em Teste", Value = "Em Teste"},
                new SelectListItem{Text = "Done", Value = "Done"}
            };
            return View();
        }
        [HttpPost]
        public ActionResult Create(ReleaseBacklog RB)
        {
            _RBacklogRep.ADD(RB);
            Session["Lista"] = RBacklogList;
            CarregaLista();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {
            CarregaLista();
            return View(RBacklogList.Where(X => X.ID == id).First());
        }
        [HttpPost]
        public ActionResult Delete(ReleaseBacklog RB)
        {
            CarregaLista();
            _RBacklogRep.Delete(RBacklogList.Where(X => X.ID == RB.ID).First());
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            CarregaLista();
            //passando uma model A
            ReleaseBacklog A = RBacklogList.Where(X => X.ID == id).First();
            List<Equipe> Equipes = (List<Equipe>)Session["Equipes"];
            ProductList = _ProductRep.Lista(new ProductBacklogMapper());
            ViewBag.Historia = new SelectList(ProductList, "ID", "Historia");

            UserList = _UserRep.Lista(new UsersMapper());
            ViewBag.Nome = new SelectList(UserList, "ID", "Nome");

            ViewBag.Situacao = new List<SelectListItem>
            {
                new SelectListItem{Text = "A Fazer", Value = "A Fazer"},
                new SelectListItem{Text = "Em Execução", Value = "Em Execução"},
                new SelectListItem{Text = "Em Teste", Value = "Em Teste"},
                new SelectListItem{Text = "Done", Value = "Done"}
            };
            return View(A);
        }

        [HttpPost]
        public ActionResult Edit(ReleaseBacklog RB)
        {
            //carrega lista e traz um objeto da lista para ser editado
            CarregaLista();
            _RBacklogRep.Update(RB);
            Session["Lista"] = RBacklogList;
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            CarregaLista();
            return View(RBacklogList.Where(X => X.ID == id).First());
        }
    }
}

Ferramenta_Scrumt/Views/Quadrotarefas/Details.cshtml
@model Ferramenta_Scrumt.MODEL.Quadro_tarefas

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Detalhes da História</h4>
        </div>
        <div class="modal-body">
            <p>História: @Html.DisplayFor(model => model.Historia)</p>
            <p>Projeto: @Html.DisplayFor(model => model.Projeto)</p>
            <p>Situação: @Html.DisplayFor(model => model.Situacao)</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
        </div>
    </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->

Ferramenta_Scrumt/Views/Quadrotarefas/Index.cshtml
@model IEnumerable<Ferramenta_Scrumt.MODEL.Quadro_tarefas>

@{
    ViewBag.Title = "Quadro de Tarefas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .sortable-todo {
        list-style-type: none;
        min-height: 10px;
    }
    .sortable-description {
        border-radius: 3px;
        color: #7f8b97;
        line-height: 1.3;
        padding: 20px;
        text-align: center;
    }
</style>
<div class="page-heading">
    <h3>
        Quadro de Tarefas
    </h3>
    <div class="col-md-offset-7 col-md-1 col-xs-8">
        <label class="col-lg-2 col-sm-2 control-label">Projeto</label>
    </div>
    <div class="col-md-2 col-xs-8">
        @Html.DropDownList("Descricao", (SelectList)ViewBag.Projeto,"Selecione", htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="col-md-2 col-xs-8">
        <p>
            <button class="btn btn-info" onclick="location.href='@Url.Action("Index", "ReleaseBacklog")'" type="button">Release Backlog</button>
        </p>
    </div>
</div>
<div class="wrapper">

    <div class="col-md-3">
        <div class="panel">
            <header class="panel-heading">
                A Fazer
            </header>
            <div class="panel-body">
                <ul class="to-do-list sortable-todo">
                @foreach (var item in Model)
                {
                    <p>
                        @if (item.Situacao == "A Fazer")
                        {
                        <li class="clearfix">
                            <p class="todo-title">
                                
                                    @Html.DisplayFor(modelItem => item.Historia)
                                    @if (item.Importancia == "Alta")
                                    {
                                        <span class="label label-danger">Alta</span>
                                    }
                                    @if (item.Importancia == "Média")
                                    {
                                        <span class="label label-warning">Média</span>
                                    }
                                    @if (item.Importancia == "Baixa")
                                    {
                                        <span class="label label-success">Baixa</span>
                                    }
                                <a href="#" class="menu-icon btndetails pull-right" data-value="@item.id_Pbacklog"></a>
                            </p>
                        </li>
                        }
                        
                    </p>
                }
                </ul>
                
            </div>
        </div>
        <p class="sortable-description">Tarefas que precisam ser feitas</p>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <header class="panel-heading">
                Em Execução
            </header>
            <div class="panel-body">
                <ul class="to-do-list sortable-todo">
                    @foreach (var item in Model)
                    {
                        <span>
                            @if (item.Situacao == "Em Execução")
                            {
                                <li class="clearfix">
                                    <p class="todo-title">

                                        @Html.DisplayFor(modelItem => item.Historia)
                                        @if (item.Importancia == "Alta")
                                        {
                                            <span class="label label-danger">Alta</span>
                                        }
                                        @if (item.Importancia == "Média")
                                        {
                                            <span class="label label-warning">Média</span>
                                        }
                                        @if (item.Importancia == "Baixa")
                                        {
                                            <span class="label label-success">Baixa</span>
                                        }
                                        <a href="#" class="menu-icon btndetails pull-right" data-value="@item.id_Pbacklog"></a>
                                    </p>
                                </li>
                            }

                        </span>
                    }

                </ul>
                
            </div>
        </div>
        <p class="sortable-description">Tarefas que está trabalhando</p>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <header class="panel-heading">
                Em Teste
            </header>
            <div class="panel-body">
                <ul class="to-do-list sortable-todo">
                    @foreach (var item in Model)
                    {
                        <span>
                            @if (item.Situacao == "Em Teste")
                            {
                                <li class="clearfix">
                                    <p class="todo-title">
                                        @Html.DisplayFor(modelItem => item.Historia)
                                        @if (item.Importancia == "Alta")
                                        {
                                            <span class="label label-danger">Alta</span>
                                        }
                                        @if (item.Importancia == "Média")
                                        {
                                            <span class="label label-warning">Média</span>
                                        }
                                        @if (item.Importancia == "Baixa")
                                        {
                                            <span class="label label-success">Baixa</span>
                                        }
                                        <a href="#" class="menu-icon btndetails pull-right" data-value="@item.id_Pbacklog"></a>
                                    </p>
                                </li>
                            }
                        </span>
                    }
                </ul>
            </div>
        </div>
        <p class="sortable-description">Testes estão sendo realizados</p>
    </div>
    <div class="col-md-3">
        <div class="panel">
            <header class="panel-heading">
                Done (Pronto)
            </header>
            <div class="panel-body">
                <ul class="to-do-list sortable-todo" >
                    @foreach (var item in Model)
                    {
                        <span>
                            @if (item.Situacao == "Done")
                            {
                                <li class="clearfix">
                                    <p class="todo-title">

                                        @Html.DisplayFor(modelItem => item.Historia)
                                        @if (item.Importancia == "Alta")
                                        {
                                            <span class="label label-danger">Alta</span>
                                        }
                                        @if (item.Importancia == "Média")
                                        {
                                            <span class="label label-warning">Média</span>
                                        }

                                        @if (item.Importancia == "Baixa")
                                        {
                                            <span class="label label-success">Baixa</span>
                                        }
                                        <a href="#" class="menu-icon btndetails pull-right" data-value="@item.id_Pbacklog"></a>
                                    </p>
                                </li>
                            }
                        </span>
                    }
                </ul>
            </div>
        </div>
        <p class="sortable-description">Tarefas finalizadas. Parabéns!</p>
    </div>

</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

</div>
@section scripts{

    <script type="text/javascript">

        $(document).ready(function () {

            $.ajaxSetup({ cache: true });

            $(".btndetails").click(function () {
                var id = $(this).data("value");
                $("#myModal").load("/Quadrotarefas/Details/" + id, function () {
                    $('#myModal').modal("show");
                });
            });
        });

    </script>
}